name: Generate Previews

on:
  workflow_dispatch:

jobs:
  generate-previews:
    name: Generate Previews
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium

    - name: Download latest Simple Icons release
      run: |
        curl -L "https://github.com/simple-icons/simple-icons/archive/refs/tags/14.6.0.zip" -o "simple-icons-14.6.0.zip"

    - name: Extract Simple Icons
      run: |
        unzip "simple-icons-14.6.0.zip"

    - name: Move icon files
      run: |
        mkdir -p assets/icons
        cp -r simple-icons-14.6.0/icons/* assets/icons
    
    - name: Generate previews
      run: python ./assets/render-previews.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add assets/previews
        git commit -m "Generate previews"
        git push