name: Release a New Version of Simple Icons Streamdeck
on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '0 9 * * 1'
jobs:
    build:
        name: Release a New Version of Simple Icons Streamdeck
        timeout-minutes: 10
        runs-on: windows-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Read version from manifest.json
              id: manifestJson
              uses: RadovanPelka/github-action-json@main
              with:
                path: 'template/manifest.json'

            - name: Increment version number
              run: |
                VERSION=$(echo "${{ steps.packageJson.outputs.version }}")
                IFS='.' read -ra VER <<< "$VERSION"
                ((VER[2]++))
                echo "NEW_VERSION=${VER[0]}.${VER[1]}.${VER[2]}" >> $GITHUB_OUTPUT
            
            - name: Set version in manifest.json
              id: packageJson
              uses: RadovanPelka/github-action-json@main
              with:
                path: 'template/manifest.json'
                replaceWith: |
                    {
                        "Version": "${{ steps.incrementVersion.outputs.NEW_VERSION }}"
                    }

            - name: Echo version file
              run: |
                cat template/manifest.json